### ISSUE TITLE
End-to-end Simulation in Main

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snitch_cluster#9]
List of tasks to do for end-to-end simulation to get into main:

- [x] Snitch core CSR decoding > @rgantonio PR #7 
- [x] Snitch core cluster and cluster connections > @rgantonio PR #6 
- [x] Add HWPE MAC to bender > @xiaoling-yi PR #10 
- [x] Add HWPE files > @xiaoling-yi #12 
- [x] Attach MAC unit > @xiaoling-yi #13 
- [x] Modify templates and schema > @xiaoling-yi @rgantonio #14 
- [x] Add SNAX configuration > @xiaoling-yi @rgantonio #14 
- [x] Add working CSR test > @rgantonio #15

**Comment by rgantonio** [comment]
Done!!!
